
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-gray-900 border-t border-gray-800 mt-12">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-6 text-center text-gray-500">
        <p>&copy; {new Date().getFullYear()} Project2028.com. All Rights Reserved.</p>
        <p className="text-sm mt-1">Information generated by AI and is intended for informational purposes only. Please verify all data.</p>
      </div>
    </footer>
  );
};

export default Footer;
